add spellhandler's specific TooltipDelve infos for 1.110+
Dawn-of-Light/DOLSharp pull request #317
Opened 2021-06-25 00:08 UTC by JVirant

The purpose of this commit is to give a better tooltip for spells with 1.110+.
It's clearly not 100% correct but it's a really big task to do it, I extracted all possible "Function" keywords:
```
absorb
accuracy
add_effect
add_radius
addattack
af_hit
amnesia
araisedead
archery
archmagery
armorpiece_debuff
arrogant
aura
autores
bainshee_pulse
ball
battery
bedazzle
bolt
breath
buff_shear
charm
climb
combat
combat_heal
cost_reduction
cower
critical
crit_buff
damage
damage_type
dashing
dcharm
dconvert
def_proc
degrade
degrade_hurt
direct
direct_chain
direct_inc
disarm
disease
dmg_add
dmg_shield
dmg_suppress
dmg_to_power
doppelgang
dot
dsummon
dummy
efatigue
ehealth
end_drain
enhance_ab
enhancement
epower
fat_heal
fatigue
feather
font
g_absorb
gate
grapple
gsummon
haste
heal
heal_bonus
healsight
hit_buffer
hold_storm
ill_animist
ill_bard
ill_bone
illusion
invisible
item
level
lifedrain
light
lull
mag_pierce
mez_dampen
mod
nabsorb
narchmage
narrogant
nbonus
ndamage
ndisorient
nencumber
nfatigue
nhidden
nillusion
no_cost
nradius
nresist_dam
nresistance
nshield
nskill
nstat
nstat_block
nstat_fade
nstat_perc
nstatdrain
nstyle
ntarget
ntransfer
ntwostat
nullskill
nweaponskill
off_proc
olife_drain
omni_heal
paralyze
petcast
plifedrain
power_heal
power_xfer
powerdrain
preserve
proj_shield
pshield
purge
queue
raise_dead
realmlore
reclaim
recover
regen
regen_perc
rem_eff_ty
rem_rnd_buf
remove_eff
reset_qc
resistance
reveal
rune
rune_sweep
s_predict
sever
shield
siege
siege_protection
skill
snare
snare_dampen
soff_proc
sp_suppress
speedwarp
spell_pulse
spreadheal
ssummon
stat
storm
styleheal
summon
suppress
taunt
teleport
tempest
transfer
true_speed
twostat
vanish
vision
vortex
xrbchp_bonus
xrecover
```

Many of them are not for spells but it can help to find some function used by spells.

2021-06-28 12:24 UTC, Lotendan commented on GameServer/spells/ResistBuff.cs
> +			dw.AddKeyValuePair("parm", "16");
Can this parameter be factorized above under the AbstractResistBuff? Plus this is likely the same for resist debuffs, isn't it?

2021-06-28 12:24 UTC, Lotendan commented on GameServer/spells/ResurrectSpellHandler.cs
> +			dw.AddKeyValuePair("target", "8");
Target "Corpse" should be handler at SpellHandler level in my opinion.

2021-06-28 12:24 UTC, Lotendan commented on GameServer/spells/ResurrectSpellHandler.cs
> +			dw.AddKeyValuePair("amount_increase", Spell.ResurrectMana);
`amount_increase` and `type1` unused here.

2021-06-28 18:22 UTC, JVirant commented on GameServer/packets/Utils/MiniDelveWriter.cs
> +		public void AddKeyValuePair(string name, eDamageType val)
Thanks!

2021-06-28 19:10 UTC, JVirant commented on GameServer/spells/CureDiseaseSpellHandler.cs
> +			dw.AddKeyValuePair("Function", "rem_eff_ty");
For now, I prefer to keep it simple, when we will have every values, it may be a good idea to refactor this part.

2021-07-28 14:49 UTC, NetDwarf requested changes
I really postponed that for quite some time, because my review amounts basically to "Please make it readable.". The issue with readability is however already in the SpellHandler.TooltipDelve(ref MiniDelveWriter) which is not new. It was just invisible to me up until this point.

My proposed change would be JVirant/DOLSharp#2. Basically replacing SpellHandler.TooltipDelve(ref MiniDelveWriter) with .ShortDescription and .CostType (also adding Endurance).

2021-09-16 16:07 UTC, NetDwarf commented
I guess I made a mistake and should have just merged it.

2021-09-16 16:07 UTC, merged